#!/bin/bash

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all --no-zsh --no-fish

flatpak install --noninteractive --or-update \
	com.github.tchx84.Flatseal \
	io.neovim.nvim
